name: Build

on:
  push:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Make
      run: make

    - name: Porcelain
      run: |
        go mod tidy
        test -z "$(git status --porcelain)" || (git status; git diff; false)

    - name: Redeploy Docs
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: evcc-io/docs
        event-type: evcc-config-updated
